# Generated by Django 4.2 on 2025-08-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='berries',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='order',
            name='decor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='form',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='order',
            name='levels',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Уровни'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_comments',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Топпинг'),
        ),
        migrations.AddField(
            model_name='order',
            name='words',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Надпись'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.JSONField(default=dict, verbose_name='Детали заказа'),
        ),
    ]
